# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppTestEntry <- function() {
    .Call('spatialSEIR_rcppTestEntry', PACKAGE = 'spatialSEIR')
}

spatialSEIRInit <- function(compMatDim, xDim, zDim, S0_, E0_, I0_, R0_, Sstar0, Estar0, Istar0, Rstar0, Istar, X_, Z_) {
    .Call('spatialSEIR_spatialSEIRInit', PACKAGE = 'spatialSEIR', compMatDim, xDim, zDim, S0_, E0_, I0_, R0_, Sstar0, Estar0, Istar0, Rstar0, Istar, X_, Z_)
}

