# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppTestEntry <- function() {
    .Call('spatialSEIR_rcppTestEntry', PACKAGE = 'spatialSEIR')
}

spatialSEIRInit <- function(compMatDim, xDim, zDim, S0_, E0_, I0_, R0_, Sstar0, Estar0, Istar0, Rstar0, Sstar, Estar, Istar, Rstar, X_, Z_, DistMat_, rho_, gamma_, priorAlpha_gamma_, priorBeta_gamma_, beta_, p_ei_, p_ir_, p_rs_, N_, outFile, logVarList, iterationStride, verboseFlag, debugFlag, sliceWidths) {
    .Call('spatialSEIR_spatialSEIRInit', PACKAGE = 'spatialSEIR', compMatDim, xDim, zDim, S0_, E0_, I0_, R0_, Sstar0, Estar0, Istar0, Rstar0, Sstar, Estar, Istar, Rstar, X_, Z_, DistMat_, rho_, gamma_, priorAlpha_gamma_, priorBeta_gamma_, beta_, p_ei_, p_ir_, p_rs_, N_, outFile, logVarList, iterationStride, verboseFlag, debugFlag, sliceWidths)
}

