// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcppTestEntry
List rcppTestEntry();
RcppExport SEXP spatialSEIR_rcppTestEntry() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = rcppTestEntry();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// spatialSEIRInit
SEXP spatialSEIRInit(SEXP compMatDim, SEXP xDim, SEXP zDim, SEXP xPrsDim, SEXP S0_, SEXP E0_, SEXP I0_, SEXP R0_, SEXP Sstar0, SEXP Estar0, SEXP Istar0, SEXP Rstar0, SEXP Sstar, SEXP Estar, SEXP Istar, SEXP Rstar, SEXP X_, SEXP Z_, SEXP X_pRS_, SEXP DistMat_, SEXP rho_, SEXP gamma_, SEXP priorAlpha_gamma_, SEXP priorBeta_gamma_, SEXP priorAlpha_pEI_, SEXP priorBeta_pEI_, SEXP priorAlpha_pIR_, SEXP priorBeta_pIR_, SEXP beta_, SEXP betaPrs_, SEXP betaPrsPriorPrecision_, SEXP p_ei_, SEXP p_ir_, SEXP N_, SEXP outFile, SEXP logVarList, SEXP iterationStride, SEXP verboseFlag, SEXP debugFlag, SEXP sliceWidths, SEXP wrapTimeSeries);
RcppExport SEXP spatialSEIR_spatialSEIRInit(SEXP compMatDimSEXP, SEXP xDimSEXP, SEXP zDimSEXP, SEXP xPrsDimSEXP, SEXP S0_SEXP, SEXP E0_SEXP, SEXP I0_SEXP, SEXP R0_SEXP, SEXP Sstar0SEXP, SEXP Estar0SEXP, SEXP Istar0SEXP, SEXP Rstar0SEXP, SEXP SstarSEXP, SEXP EstarSEXP, SEXP IstarSEXP, SEXP RstarSEXP, SEXP X_SEXP, SEXP Z_SEXP, SEXP X_pRS_SEXP, SEXP DistMat_SEXP, SEXP rho_SEXP, SEXP gamma_SEXP, SEXP priorAlpha_gamma_SEXP, SEXP priorBeta_gamma_SEXP, SEXP priorAlpha_pEI_SEXP, SEXP priorBeta_pEI_SEXP, SEXP priorAlpha_pIR_SEXP, SEXP priorBeta_pIR_SEXP, SEXP beta_SEXP, SEXP betaPrs_SEXP, SEXP betaPrsPriorPrecision_SEXP, SEXP p_ei_SEXP, SEXP p_ir_SEXP, SEXP N_SEXP, SEXP outFileSEXP, SEXP logVarListSEXP, SEXP iterationStrideSEXP, SEXP verboseFlagSEXP, SEXP debugFlagSEXP, SEXP sliceWidthsSEXP, SEXP wrapTimeSeriesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type compMatDim(compMatDimSEXP );
        Rcpp::traits::input_parameter< SEXP >::type xDim(xDimSEXP );
        Rcpp::traits::input_parameter< SEXP >::type zDim(zDimSEXP );
        Rcpp::traits::input_parameter< SEXP >::type xPrsDim(xPrsDimSEXP );
        Rcpp::traits::input_parameter< SEXP >::type S0_(S0_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type E0_(E0_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type I0_(I0_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type R0_(R0_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type Sstar0(Sstar0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type Estar0(Estar0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type Istar0(Istar0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type Rstar0(Rstar0SEXP );
        Rcpp::traits::input_parameter< SEXP >::type Sstar(SstarSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Estar(EstarSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Istar(IstarSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Rstar(RstarSEXP );
        Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type Z_(Z_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type X_pRS_(X_pRS_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type DistMat_(DistMat_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type rho_(rho_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type gamma_(gamma_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type priorAlpha_gamma_(priorAlpha_gamma_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type priorBeta_gamma_(priorBeta_gamma_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type priorAlpha_pEI_(priorAlpha_pEI_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type priorBeta_pEI_(priorBeta_pEI_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type priorAlpha_pIR_(priorAlpha_pIR_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type priorBeta_pIR_(priorBeta_pIR_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta_(beta_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type betaPrs_(betaPrs_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type betaPrsPriorPrecision_(betaPrsPriorPrecision_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type p_ei_(p_ei_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type p_ir_(p_ir_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type N_(N_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type outFile(outFileSEXP );
        Rcpp::traits::input_parameter< SEXP >::type logVarList(logVarListSEXP );
        Rcpp::traits::input_parameter< SEXP >::type iterationStride(iterationStrideSEXP );
        Rcpp::traits::input_parameter< SEXP >::type verboseFlag(verboseFlagSEXP );
        Rcpp::traits::input_parameter< SEXP >::type debugFlag(debugFlagSEXP );
        Rcpp::traits::input_parameter< SEXP >::type sliceWidths(sliceWidthsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type wrapTimeSeries(wrapTimeSeriesSEXP );
        SEXP __result = spatialSEIRInit(compMatDim, xDim, zDim, xPrsDim, S0_, E0_, I0_, R0_, Sstar0, Estar0, Istar0, Rstar0, Sstar, Estar, Istar, Rstar, X_, Z_, X_pRS_, DistMat_, rho_, gamma_, priorAlpha_gamma_, priorBeta_gamma_, priorAlpha_pEI_, priorBeta_pEI_, priorAlpha_pIR_, priorBeta_pIR_, beta_, betaPrs_, betaPrsPriorPrecision_, p_ei_, p_ir_, N_, outFile, logVarList, iterationStride, verboseFlag, debugFlag, sliceWidths, wrapTimeSeries);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
